{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

{
  nixpkgs = {
    config = {
      allowUnfree = true;
    };
  };
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = "adrian";
  home.homeDirectory = "/home/adrian";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.11"; # Please read the comment before changing.

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    gnome-tweaks

    font-awesome
    nerd-fonts.caskaydia-cove
    nerd-fonts.hack
    opencode
    nodejs
    gh
  ];

  fonts.fontconfig.enable = true;

  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
    # Native node modules loaded by some OpenCode plugins (e.g. native addons /
    # napi bindings) need libstdc++. Nix-built binaries use the Nix dynamic
    # linker which doesn't search FHS paths, so we must expose it explicitly.
    LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib";
    # Enable oh-my-opencode-slim background subagents (task tool with background:true).
    # This is gated on an env var, not a config key in oh-my-opencode-slim.json.
    OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS = "true";
  };

  home.sessionPath = [ "$HOME/.local/bin" ];

  # Use the opencode.json stored in this repository as the declarative source.
  # Reference it relative to this module so Home Manager/Flakes can include it
  # in the derivation. Do NOT use an absolute path (flake evaluation is pure).
  home.file.".config/opencode/opencode.json".source = ./opencode.json;
  home.file.".config/opencode/opencode.json".force = true;

  # oh-my-openagent agent/model configuration (generated by oh-my-openagent installer).
  home.file.".config/opencode/oh-my-openagent.json".source = ./oh-my-openagent.json;
  home.file.".config/opencode/oh-my-openagent.json".force = true;

  # oh-my-opencode-slim multi-agent orchestration plugin configuration.
  home.file.".config/opencode/oh-my-opencode-slim.json".source = ./oh-my-opencode-slim.json;
  home.file.".config/opencode/oh-my-opencode-slim.json".force = true;

  # OpenCode Agent Skills — installed globally so they are available in every project.
  home.file.".config/opencode/skills/skill-creator/SKILL.md".source = ./skills/skill-creator/SKILL.md;

  # Install oh-my-opencode-slim's bundled skills into ~/.config/opencode/skills.
  #
  # The plugin ships SKILL.md files under <pkg>/src/skills/<name>/ but only its
  # standalone installer copies them into ~/.config/opencode/skills. This setup
  # is declarative and never runs that installer, so we copy them at activation.
  #
  # NOTE: The source lives in OpenCode's *mutable* plugin cache, which is only
  # populated after OpenCode has resolved the plugin at runtime. This block is
  # therefore best-effort: it copies whatever skills currently exist and no-ops
  # gracefully (without failing the switch) when the cache is not yet present
  # (e.g. fresh machine, or immediately after a cache wipe / `nix flake update`
  # before OpenCode has launched). Run `home-manager switch` again after the
  # first OpenCode launch if skills were not yet available. Skills auto-follow
  # the installed plugin version because the version dir is globbed, not pinned.
  home.activation.installSlimSkills = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    PKG_ROOT="$HOME/.cache/opencode/packages"
    SKILLS_DST="$HOME/.config/opencode/skills"

    # Resolve the plugin's skills source dir. Prefer a concrete version dir over
    # the floating @latest dir; if several exist, take the most recently built.
    SRC_SKILLS=""
    if [ -d "$PKG_ROOT" ]; then
      for cand in $(${pkgs.coreutils}/bin/ls -dt "$PKG_ROOT"/oh-my-opencode-slim@*/node_modules/oh-my-opencode-slim/src/skills 2>/dev/null); do
        if [ -d "$cand" ]; then
          SRC_SKILLS="$cand"
          break
        fi
      done
    fi

    if [ -z "$SRC_SKILLS" ]; then
      echo "installSlimSkills: plugin skills not found in cache yet; skipping." \
           "Re-run 'home-manager switch' after launching OpenCode once."
    else
      mkdir -p "$SKILLS_DST"
      copied=0
      # Only copy real skill directories (those containing a SKILL.md); this
      # skips stray top-level docs like src/skills/codemap.md.
      for skilldir in "$SRC_SKILLS"/*/; do
        if [ -f "$skilldir/SKILL.md" ]; then
          name="$(${pkgs.coreutils}/bin/basename "$skilldir")"
          # Idempotent overwrite: replace the managed copy, preserve subtrees
          # (e.g. codemap/scripts/). Does not touch other skills like
          # skill-creator, which is managed separately via home.file.
          rm -rf "$SKILLS_DST/$name"
          ${pkgs.coreutils}/bin/cp -rf "$skilldir" "$SKILLS_DST/$name"
          copied=$((copied + 1))
        fi
      done
      echo "installSlimSkills: installed $copied bundled skill(s) from $SRC_SKILLS"
    fi
  '';

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  imports = [
    ./zsh.nix
    ./nvim.nix
    ./sway/config.nix
  ];
}
